name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Extract tag name
      id: prep
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/v})"
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vvtoon-a:${{ steps.prep.outputs.tag }}
        build-args:
          DB_HOST=${{ secrets.DB_HOST }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PWD=${{ secrets.MYSQL_PWD }}
          UNSHORTEN_API=${{ secrets.UNSHORTEN_API }}
