name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PWD: ${{ secrets.MYSQL_PWD }}
      UNSHORTEN_API: ${{ secrets.UNSHORTEN_API }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: docker build \
        --build-arg DB_HOST=${{ env.DB_HOST }} \
        --build-arg DB_DATABASE=${{ env.DB_DATABASE }} \
        --build-arg MYSQL_PORT=${{ env.MYSQL_PORT }} \
        --build-arg MYSQL_USER=${{ env.MYSQL_USER }} \
        --build-arg MYSQL_PWD=${{ env.MYSQL_PWD }} \
        --build-arg UNSHORTEN_API=${{ env.UNSHORTEN_API }} \
        -t ${{ env.USERNAME }}/vvtoon-a:node .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ env.USERNAME }}/vvtoon-a:node
