name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: docker build --build-arg DB_HOST=${{ secrets.DB_HOST }} --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} --build-arg MYSQL_PORT=${{ secrets.MYSQL_PORT }} --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} --build-arg MYSQL_PWD=${{ secrets.MYSQL_PWD }} --build-arg UNSHORTEN_API=${{ secrets.UNSHORTEN_API }} -t ${{ secrets.DOCKER_USERNAME }}/vvtoon-a:node .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/vvtoon-a:node
